## BOF Admin Service Dubbo
#对应ApplicationConfig Dubbo应用配置
dubbo.application.name=hwj-basic-business-application
dubbo.application.owner=com.hwj.basic.business.application
dubbo.application.organization=hwj
dubbo.application.logger=slf4j
dubbo.application.compiler=javassist

#对应ConfigCenterConfig Dubbo内置配置中心
dubbo.config-center.address=nacos://127.0.0.1:8848?namespace=namespace-dubbo-hwj

#对应RegistryConfig Dubbo注册中心
dubbo.registries.registry-hwj.id=registry-hwj
dubbo.registries.registry-hwj.address=nacos://127.0.0.1:8848?namespace=namespace-dubbo-hwj
dubbo.registries.registry-hwj.group=dubbo-hwj
dubbo.registries.registry-hwj.session=60000
dubbo.registries.registry-hwj.register=true
dubbo.registries.registry-hwj.subscribe=true
dubbo.registries.registry-hwj.check=true

#hwj-basic-server consumer
dubbo.consumers.consumer-hwj-basic-server.id=consumer-hwj-basic-server
dubbo.consumers.consumer-hwj-basic-server.registryIds=registry-hwj
dubbo.consumers.consumer-hwj-basic-server.init=false
dubbo.consumers.consumer-hwj-basic-server.check=true
dubbo.consumers.consumer-hwj-basic-server.retries=0
dubbo.consumers.consumer-hwj-basic-server.timeout=5000
dubbo.consumers.consumer-hwj-basic-server.group=hwj-basic-server



